# Generated by Django 3.0.6 on 2020-05-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20200523_2144'),
        ('eatery_app', '0003_auto_20200523_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
