# Generated by Django 3.0.6 on 2020-05-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20200525_0131'),
        ('eatery_app', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
